#!/bin/bash

# bash theme - partly inspired by https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/robbyrussell.zsh-theme
# from https://github.com/devcontainers/features/blob/main/src/common-utils/scripts/bash_theme_snippet.sh
__bash_prompt() {
    local userpart='`export XIT=$? \
        && echo -n "\u " \
        && [ "$XIT" -ne "0" ] && echo -n "\[\033[1;31m\]➜" || echo -n "\[\033[0m\]➜"`'
    local gitbranch='`\
        export BRANCH="$(git --no-optional-locks symbolic-ref --short HEAD 2>/dev/null || git --no-optional-locks rev-parse --short HEAD 2>/dev/null)"; \
        if [ "${BRANCH:-}" != "" ]; then \
            echo -n "\[\033[0;36m\](\[\033[1;32m\]${BRANCH:-}" \
            && if git --no-optional-locks ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*" > /dev/null 2>&1; then \
                    echo -n " \[\033[1;33m\]✗"; \
            fi \
            && echo -n "\[\033[0;36m\]) "; \
        fi`'
    local removecolor='\[\033[0m\]'
    local lightblue='\[\033[1;34m\]'
    local cyan='\[\033[0;36m\]'
    PS1="${lightblue}${userpart} ${cyan}\w ${gitbranch}${removecolor}\n\$ "
    unset -f __bash_prompt
}
__bash_prompt
export PROMPT_DIRTRIM=4

# enable enternal shared history
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=-1
export HISTFILESIZE=-1
export SAVEHIST=-1
export HISTFILE=$USER_TERMINAL_CONFIG/.bash_eternal_history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# enable bash completion for git
source /usr/share/bash-completion/completions/git

# Setup some common defaults like vscode for the git editor
source "$HOME/terminal-config/common-defaults"
