#!/bin/bash

# This bashrc will be sourced from /root/.bashrc upon launch of every terminal
# in a devcontainer that uses the ubuntu-devcontainer as a base
# https://github.com/DiamondLightSource/ubuntu-devcontainer

# This file is initialized by the devcontainer, but you are then free to edit it

# Execute default, opinionated settings:
# https://github.com/DiamondLightSource/ubuntu-devcontainer/blob/main/terminal-config/bashrc-default
# delete this line to remove defaults
source ~/terminal-config/bashrc-default

if [ ! -f ~/one-time ]; then
    # add your personal one time only (container creation) commands here
    touch ~/one-time
fi

# add your personal settings for every shell below
