#!/bin/zsh

# Set the prompt theme to robbyrussell if not already set
ZSH_THEME=${ZSH_THEME:-robbyrussell}

# Source oh my zsh, theme and plugins must be set before this
source "$HOME/.oh-my-zsh/oh-my-zsh.sh"

# Set up eternal history for zsh
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=10000000
SAVEHIST=$HISTSIZE
HISTFILE=$USER_TERMINAL_CONFIG/.zsh_eternal_history
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.

# Setup some common defaults like vscode for the git editor
source "$HOME/terminal-config/common-defaults"
